### ISSUE TITLE
Why do you call this framework a "machine learning" framework?

### ISSUE THREAD

**Issue by nbro** [LukeMathWalker/linfa#19]
Currently, this framework only provides the implementation of a single algorithm (an unsupervised algorithm), but this framework (repository) has been around for 2 years, which makes the goal of this project very questionable. Therefore, I suggest you either archive this repo or change its name or goal. It's misleading to have a repo that suggests that this is an ML framework, while it's just an implementation of a single algorithm.

**Comment by LukeMathWalker** [comment]
I suggest you take care of your own repos and manage them as you see fit :smiley:
